<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="suraj" failures="1" tests="12" name="com.vyasa.automation.testing.DemoTestNG" time="0.034" errors="0" timestamp="2022-10-06T17:03:40 IST" skipped="1">
  <testcase classname="com.vyasa.automation.testing.DemoTestNG" name="TestCase1" time="0.003">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.vyasa.automation.testing.DemoTestNG.TestCase1(DemoTestNG.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestCase1 -->
  <system-out/>
  <testcase classname="com.vyasa.automation.testing.DemoTestNG" name="TestCase5" time="0.002"/>
  <system-out/>
  <testcase classname="com.vyasa.automation.testing.DemoTestNG" name="TestCase12" time="0.002"/>
  <system-out/>
  <testcase classname="com.vyasa.automation.testing.DemoTestNG" name="TestCase11" time="0.001"/>
  <system-out/>
  <testcase classname="com.vyasa.automation.testing.DemoTestNG" name="TestCase6" time="0.002"/>
  <system-out/>
  <testcase classname="com.vyasa.automation.testing.DemoTestNG" name="TestCase3" time="0.002"/>
  <system-out/>
  <testcase classname="com.vyasa.automation.testing.DemoTestNG" name="TestCase4" time="0.001"/>
  <system-out/>
  <testcase classname="com.vyasa.automation.testing.DemoTestNG" name="TestCase7" time="0.002"/>
  <system-out/>
  <testcase classname="com.vyasa.automation.testing.DemoTestNG" name="TestCase8" time="0.002"/>
  <system-out/>
  <testcase classname="com.vyasa.automation.testing.DemoTestNG" name="TestCase9" time="0.015"/>
  <system-out/>
  <testcase classname="com.vyasa.automation.testing.DemoTestNG" name="TestCase10" time="0.002"/>
  <system-out/>
  <testcase classname="com.vyasa.automation.testing.DemoTestNG" name="TestCase2">
    <skipped/>
  </testcase> <!-- TestCase2 -->
  <system-out/>
</testsuite> <!-- com.vyasa.automation.testing.DemoTestNG -->
